name: CI - API Zodiac PHP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Docker Compose
      run: sudo apt-get install docker-compose -y
    
    - name: Build e rodar testes
      run: |
        docker-compose up -d 
        sleep 5
        docker-compose run --rm api php testes/test_signos.php
